import json
import os
import shutil
import time
import uuid
from datetime import datetime

INBOX_DIR = os.environ.get("INBOX_DIR", "/app/inbox")
ARCHIVE_DIR = os.environ.get("ARCHIVE_DIR", "/app/archive")
STAGING_DIR = os.environ.get("STAGING_DIR", "/app/staging")
POLL_INTERVAL = float(os.environ.get("POLL_INTERVAL", "5"))


def iso_now() -> str:
    return datetime.utcnow().isoformat() + "Z"


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def build_sidecar(src_path: str, archive_path: str, item_type: str) -> dict:
    return {
        "id": str(uuid.uuid4()),
        "source_path": src_path,
        "archived_path": archive_path,
        "item_type": item_type,
        "created_at": iso_now(),
        "text": "TODO: extract text from source (stub pipeline).",
        "notes": "Placeholder sidecar generated by ETL scaffold.",
    }


def process_file(src_path: str, rel_dir: str, filename: str) -> None:
    item_type = rel_dir.split(os.sep)[0] if rel_dir else "unknown"
    archive_subdir = os.path.join(ARCHIVE_DIR, rel_dir)
    ensure_dir(archive_subdir)
    ensure_dir(STAGING_DIR)

    archived_path = os.path.join(archive_subdir, filename)
    sidecar = build_sidecar(src_path, archived_path, item_type)
    sidecar_name = f"{os.path.splitext(filename)[0]}.json"
    sidecar_archive_path = os.path.join(archive_subdir, sidecar_name)
    sidecar_staging_path = os.path.join(STAGING_DIR, sidecar_name)

    # Move original into archive
    shutil.move(src_path, archived_path)

    # Write sidecar into archive
    with open(sidecar_archive_path, "w", encoding="utf-8") as f:
        json.dump(sidecar, f, ensure_ascii=False, indent=2)

    # Copy sidecar into staging for immediate embedding
    shutil.copy2(sidecar_archive_path, sidecar_staging_path)
    print(f"[ETL] Archived {filename} -> {archived_path}, sidecar -> {sidecar_staging_path}")


def scan_once() -> None:
    for root, _, files in os.walk(INBOX_DIR):
        rel_dir = os.path.relpath(root, INBOX_DIR)
        if rel_dir == ".":
            rel_dir = ""
        for name in files:
            if name.startswith("."):
                continue
            src_path = os.path.join(root, name)
            try:
                process_file(src_path, rel_dir, name)
            except Exception as exc:  # noqa: BLE001
                print(f"[ETL] Failed to process {src_path}: {exc}")


def main() -> None:
    print(f"[ETL] Watching inbox {INBOX_DIR} -> archive {ARCHIVE_DIR}, staging {STAGING_DIR}")
    ensure_dir(INBOX_DIR)
    ensure_dir(ARCHIVE_DIR)
    ensure_dir(STAGING_DIR)
    while True:
        scan_once()
        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
